const operatorData = [
    // ATTACKERS
    { name: "Ace", role: "Attacker", weapons: [{ name: "AK-12", x: 0, y: 14 }, { name: "M1014", x: 1, y: 2 }, { name: "P9", x: 1, y: 1 }] },
    { name: "Amaru", role: "Attacker", weapons: [{ name: "G8A1", x: -1, y: 13 }, { name: "SuperNova", x: 1, y: 10 }, { name: "Gonne-6", x: 1, y: 4 }, { name: "SMG-11", x: 1, y: 9 }, { name: "ITA12S", x: 1, y: 2 }] },
    { name: "Ash", role: "Attacker", weapons: [{ name: "G36C", x: 1, y: 11 }, { name: "R4-C", x: 0, y: 18 }, { name: "5.7 USG", x: 1, y: 3 }, { name: "M45 MEUSOC", x: 1, y: 3 }] },
    { name: "Blackbeard", role: "Attacker", weapons: [{ name: "MK17", x: 2, y: 8 }, { name: "SR-25", x: 0, y: 5 }] },
    { name: "Blitz", role: "Attacker", weapons: [{ name: "G52-Tactical Shield", x: 0, y: 0 }, { name: "P12", x: 1, y: 2 }] },
    { name: "Brava", role: "Attacker", weapons: [{ name: "PARA-308", x: 0, y: 11 }, { name: "CAMRS", x: 0, y: 11 }, { name: "USP40", x: 1, y: 3 }, { name: "Super Shorty", x: 1, y: 2 }] },
    { name: "Buck", role: "Attacker", weapons: [{ name: "C8-SFW", x: 1, y: 15 }, { name: "CAMRS", x: 0, y: 11 }, { name: "Mk1 9mm", x: 1, y: 3 }] },
    { name: "Capitao", role: "Attacker", weapons: [{ name: "M249 SAW", x: 0, y: 12 }, { name: "PARA-308", x: 0, y: 11 }, { name: "PMR90A2", x: 1, y: 6 }, { name: "Gonne-6", x: 1, y: 4 }, { name: "PRB92", x: 1, y: 3 }] },
    { name: "Deimos", role: "Attacker", weapons: [{ name: "AK-74M", x: -1, y: 11 }, { name: "M590A1", x: 1, y: 2 }, { name: "Vendetta", x: 1, y: 7 }] },
    { name: "Dokkaebi", role: "Attacker", weapons: [{ name: "Mk 14 EBR", x: -1, y: 15 }, { name: "BOSG.12.2", x: 0, y: 5 }, { name: "Gonne-6", x: 1, y: 4 }, { name: "SMG-12", x: 2, y: 10 }, { name: "C75 Auto", x: 1, y: 8 }] },
    { name: "Finka", role: "Attacker", weapons: [{ name: "6P41", x: 1, y: 12 }, { name: "SASG-12", x: 1, y: 2 }, { name: "Spear .308", x: 0, y: 16 }, { name: "GSh-18", x: 1, y: 3 }, { name: "PMM", x: 1, y: 3 }] },
    { name: "Flores", role: "Attacker", weapons: [{ name: "AR33", x: 1, y: 11 }, { name: "SR-25", x: 0, y: 5 }, { name: "T-95 LSW", x: 1, y: 12 }, { name: "GSh-18", x: 1, y: 3 }] },
    { name: "Fuze", role: "Attacker", weapons: [{ name: "AK-12", x: 0, y: 14 }, { name: "6P41", x: 1, y: 12 }, { name: "Ballistic Shield", x: 0, y: 0 }, { name: "PMM", x: 1, y: 3 }, { name: "GSh-18", x: 1, y: 3 }] },
    { name: "Glaz", role: "Attacker", weapons: [{ name: "OTs-03", x: 0, y: 11 }, { name: "PMM", x: 1, y: 3 }, { name: "Gonne-6", x: 1, y: 4 }, { name: "Bearing 9", x: 1, y: 8 }] },
    { name: "Gridlock", role: "Attacker", weapons: [{ name: "F90", x: 0, y: 10 }, { name: "M249 SAW", x: 0, y: 12 }, { name: "Super Shorty", x: 1, y: 2 }, { name: "SDP 9mm", x: 1, y: 3 }] },
    { name: "Grim", role: "Attacker", weapons: [{ name: "552 Commando", x: 1, y: 11 }, { name: "SG-CQB", x: 1, y: 2 }, { name: "Bailiff 410", x: 0, y: 17 }, { name: "P229", x: 1, y: 3 }] },
    { name: "Hibana", role: "Attacker", weapons: [{ name: "SuperNova", x: 1, y: 10 }, { name: "Type-89", x: 0, y: 14 }, { name: "PMR90A2", x: 1, y: 6 }, { name: "Bearing 9", x: 1, y: 8 }, { name: "P229", x: 1, y: 3 }] },
    { name: "Iana", role: "Attacker", weapons: [{ name: "ARX200", x: 1, y: 13 }, { name: "G36C", x: 1, y: 11 }, { name: "Gonne-6", x: 1, y: 4 }, { name: "Mk1 9mm", x: 1, y: 3 }] },
    { name: "IQ", role: "Attacker", weapons: [{ name: "AUG A2", x: 1, y: 14 }, { name: "552 Commando", x: 1, y: 11 }, { name: "G8A1", x: -1, y: 13 }, { name: "P12", x: 1, y: 2 }] },
    { name: "Jackal", role: "Attacker", weapons: [{ name: "C7E", x: 1, y: 15 }, { name: "PDW9", x: 1, y: 8 }, { name: "ITA12L", x: 1, y: 2 }, { name: "USP40", x: 1, y: 3 }, { name: "ITA12S", x: 1, y: 2 }] },
    { name: "Kali", role: "Attacker", weapons: [{ name: "CSRX 300", x: 0, y: 1 }, { name: "SPSMG9", x: 1, y: 8 }, { name: "C75 Auto", x: 1, y: 8 }, { name: "P226 Mk 25", x: 1, y: 3 }] },
    { name: "Lion", role: "Attacker", weapons: [{ name: "417", x: 0, y: 11 }, { name: "SG-CQB", x: 1, y: 2 }, { name: "V308", x: 1, y: 11 }, { name: "LFP586", x: 1, y: 3 }, { name: "P9", x: 1, y: 1 }] },
    { name: "Maverick", role: "Attacker", weapons: [{ name: "AR-15.50", x: 1, y: 7 }, { name: "M4", x: 1, y: 6 }, { name: "1911 TACOPS", x: 1, y: 3 }, { name: "C75 Auto", x: 1, y: 8 }, { name: "Reaper MK2", x: 1, y: 4 }] },
    { name: "Montagne", role: "Attacker", weapons: [{ name: "LE ROC SHIELD", x: 0, y: 0 }, { name: "P9", x: 1, y: 1 }, { name: "LFP586", x: 1, y: 3 }] },
    { name: "Nokk", role: "Attacker", weapons: [{ name: "FMG-9", x: 1, y: 16 }, { name: "SIX12 SD", x: 1, y: 2 }, { name: "PMR90A2", x: 1, y: 6 }, { name: "5.7 USG", x: 1, y: 3 }, { name: "D-50", x: 1, y: 3 }] },
    { name: "Nomad", role: "Attacker", weapons: [{ name: "AK-74M", x: -1, y: 11 }, { name: "ARX200", x: -1, y: 10 }, { name: "PRB92", x: 1, y: 3 }, { name: ".44 MAG SEMI-AUTO", x: 1, y: 3 }] },
    { name: "Osa", role: "Attacker", weapons: [{ name: "556XI", x: 0, y: 12 }, { name: "PDW9", x: 1, y: 8 }, { name: "PMM", x: 1, y: 3 }] },
    { name: "Ram", role: "Attacker", weapons: [{ name: "LMG-E", x: 1, y: 12 }, { name: "R4-C", x: 0, y: 18 }, { name: "Mk1 9mm", x: 1, y: 3 }] },
    { name: "Rauora", role: "Attacker", weapons: [{ name: "417", x: 0, y: 11 }, { name: "M249 SAW", x: 0, y: 12 }, { name: "Reaper MK2", x: 1, y: 4 }, { name: "GSh-18", x: 1, y: 3 }] },
    { name: "Sens", role: "Attacker", weapons: [{ name: "417", x: 0, y: 11 }, { name: "POF-9", x: 1, y: 12 }, { name: "SDP 9mm", x: 1, y: 3 }] },
    { name: "Sledge", role: "Attacker", weapons: [{ name: "L85A2", x: 1, y: 10 }, { name: "M590A1", x: 1, y: 2 }, { name: "P226 Mk 25", x: 1, y: 3 }, { name: "Reaper MK2", x: 1, y: 4 }] },
    { name: "Solid Snake", role: "Attacker", weapons: [{ name: "F2", x: 0, y: 25 }, { name: "PMR90A2", x: 1, y: 6 }, { name: "TACIT .45", x: 1, y: 4 }] },
    { name: "Striker", role: "Attacker", weapons: [{ name: "M4", x: 0, y: 11 }, { name: "M249 SAW", x: 0, y: 12 }, { name: "SR-25", x: 0, y: 5 }, { name: "5.7 USG", x: 1, y: 3 }, { name: "ITA12S", x: 1, y: 2 }] },
    { name: "Thatcher", role: "Attacker", weapons: [{ name: "AR33", x: 1, y: 11 }, { name: "L85A2", x: 1, y: 9 }, { name: "M590A1", x: 1, y: 2 }, { name: "PMR90A2", x: 1, y: 6 }, { name: "P226 Mk 25", x: 1, y: 3 }] },
    { name: "Thermite", role: "Attacker", weapons: [{ name: "556XI", x: 2, y: 10 }, { name: "M1014", x: 1, y: 2 }, { name: "5.7 USG", x: 1, y: 3 }, { name: "M45 MEUSOC", x: 1, y: 3 }, { name: "ITA12S", x: 1, y: 2 }] },
    { name: "Twitch", role: "Attacker", weapons: [{ name: "F2", x: 0, y: 25 }, { name: "417", x: 0, y: 11 }, { name: "SG-CQB", x: 1, y: 2 }, { name: "P9", x: 1, y: 1 }, { name: "LFP586", x: 1, y: 3 }] },
    { name: "Ying", role: "Attacker", weapons: [{ name: "T-95 LSW", x: 1, y: 12 }, { name: "SIX12", x: 1, y: 2 }, { name: "Q-929", x: 1, y: 3 }, { name: "Reaper MK2", x: 1, y: 4 }] },
    { name: "Zero", role: "Attacker", weapons: [{ name: "MP7", x: 1, y: 6 }, { name: "SC3000K", x: 1, y: 16 }, { name: "5.7 USG", x: 1, y: 3 }, { name: "Gonne-6", x: 1, y: 4 }] },
    { name: "Zofia", role: "Attacker", weapons: [{ name: "LMG-E", x: 1, y: 12 }, { name: "M762", x: 1, y: 11 }, { name: "RG15", x: 1, y: 3 }] },

    // DEFENDERS
    { name: "Alibi", role: "Defender", weapons: [{ name: "Mx4 Storm", x: 1, y: 6 }, { name: "ACS12", x: 1, y: 2 }, { name: "Keratos .357", x: 1, y: 3 }, { name: "Bailiff 410", x: 0, y: 17 }] },
    { name: "Aruni", role: "Defender", weapons: [{ name: "P10 RONI", x: 1, y: 6 }, { name: "Mk 14 EBR", x: 0, y: 5 }, { name: "PRB92", x: 1, y: 3 }] },
    { name: "Azami", role: "Defender", weapons: [{ name: "9x19VSN", x: 1, y: 5 }, { name: "ACS12", x: 1, y: 2 }, { name: "D-50", x: 1, y: 3 }] },
    { name: "Bandit", role: "Defender", weapons: [{ name: "MP7", x: 1, y: 6 }, { name: "M870", x: 1, y: 2 }, { name: "P12", x: 1, y: 2 }] },
    { name: "Castle", role: "Defender", weapons: [{ name: "UMP45", x: 0, y: 3 }, { name: "M1014", x: 1, y: 2 }, { name: "5.7 USG", x: 1, y: 3 }, { name: "Super Shorty", x: 1, y: 2 }, { name: "M45 MEUSOC", x: 1, y: 3 }] },
    { name: "Caveira", role: "Defender", weapons: [{ name: "M12", x: 1, y: 4 }, { name: "SPAS-15", x: 1, y: 2 }, { name: "Luison", x: 1, y: 6 }] },
    { name: "Clash", role: "Defender", weapons: [{ name: "CCE SHIELD MK2", x: 0, y: 0 }, { name: "P-10C", x: 1, y: 3 }, { name: "SPSMG9", x: 1, y: 8 }, { name: "Super Shorty", x: 1, y: 2 }] },
    { name: "Denari", role: "Defender", weapons: [{ name: "Scorpion EVO 3", x: 1, y: 7 }, { name: "FMG-9", x: 1, y: 16 }, { name: "Glaive-12", x: 1, y: 2 }, { name: "P226 Mk 25", x: 1, y: 3 }] },
    { name: "Doc", role: "Defender", weapons: [{ name: "MP5", x: 0, y: 13 }, { name: "P90", x: 0, y: 11 }, { name: "SG-CQB", x: 1, y: 2 }, { name: "P9", x: 1, y: 1 }, { name: "LFP586", x: 1, y: 3 }, { name: "Bailiff 410", x: 0, y: 17 }] },
    { name: "Echo", role: "Defender", weapons: [{ name: "MP5SD", x: 1, y: 12 }, { name: "SuperNova", x: 1, y: 10 }, { name: "Bearing 9", x: 1, y: 8 }, { name: "P229", x: 1, y: 3 }] },
    { name: "Ela", role: "Defender", weapons: [{ name: "Scorpion EVO 3", x: 1, y: 7 }, { name: "FO-12", x: 1, y: 2 }, { name: "RG15", x: 1, y: 3 }] },
    { name: "Fenrir", role: "Defender", weapons: [{ name: "MP7", x: 1, y: 6 }, { name: "SASG-12", x: 1, y: 2 }, { name: "5.7 USG", x: 1, y: 3 }] },
    { name: "Frost", role: "Defender", weapons: [{ name: "Super 90", x: 1, y: 2 }, { name: "9mm C1", x: 0, y: 10 }, { name: "Mk1 9mm", x: 1, y: 3 }, { name: "ITA12S", x: 1, y: 2 }] },
    { name: "Goyo", role: "Defender", weapons: [{ name: "Vector .45 ACP", x: 0, y: 19 }, { name: "TCSG12", x: 1, y: 21 }, { name: "P229", x: 1, y: 3 }] },
    { name: "Jager", role: "Defender", weapons: [{ name: "M870", x: 1, y: 2 }, { name: "416-C Carbine", x: 1, y: 11 }, { name: "P12", x: 1, y: 2 }] },
    { name: "Kaid", role: "Defender", weapons: [{ name: "AUG A3", x: 1, y: 4 }, { name: "TCSG12", x: 1, y: 21 }, { name: ".44 MAG SEMI-AUTO", x: 1, y: 3 }, { name: "LFP586", x: 1, y: 3 }] },
    { name: "Kapkan", role: "Defender", weapons: [{ name: "9x19VSN", x: 1, y: 5 }, { name: "SASG-12", x: 1, y: 2 }, { name: "PMM", x: 1, y: 3 }, { name: "GSh-18", x: 1, y: 3 }] },
    { name: "Lesion", role: "Defender", weapons: [{ name: "SIX12 SD", x: 1, y: 2 }, { name: "T-5 SMG", x: 1, y: 6 }, { name: "Q-929", x: 1, y: 3 }, { name: "Super Shorty", x: 1, y: 2 }] },
    { name: "Maestro", role: "Defender", weapons: [{ name: "ALDA 5.56", x: 1, y: 6 }, { name: "ACS12", x: 1, y: 2 }, { name: "Keratos .357", x: 1, y: 3 }, { name: "Bailiff 410", x: 0, y: 17 }] },
    { name: "Melusi", role: "Defender", weapons: [{ name: "MP5", x: 1, y: 5 }, { name: "Super 90", x: 1, y: 2 }, { name: "ITA12S", x: 1, y: 2 }, { name: "RG15", x: 1, y: 3 }] },
    { name: "Mira", role: "Defender", weapons: [{ name: "Vector .45 ACP", x: 1, y: 7 }, { name: "ITA12L", x: 1, y: 2 }, { name: "USP40", x: 1, y: 3 }, { name: "ITA12S", x: 1, y: 2 }] },
    { name: "Mozzie", role: "Defender", weapons: [{ name: "Commando 9", x: 1, y: 5 }, { name: "P10 RONI", x: 1, y: 6 }, { name: "SDP 9mm", x: 1, y: 3 }, { name: "Super Shorty", x: 1, y: 2 }] },
    { name: "Mute", role: "Defender", weapons: [{ name: "MP5K", x: 1, y: 6 }, { name: "M590A1", x: 1, y: 2 }, { name: "P226 Mk 25", x: 1, y: 3 }, { name: "SMG-11", x: 1, y: 9 }] },
    { name: "Oryx", role: "Defender", weapons: [{ name: "SPAS-12", x: 1, y: 2 }, { name: "T-5 SMG", x: 1, y: 6 }, { name: "Bailiff 410", x: 0, y: 17 }, { name: "Reaper MK2", x: 1, y: 4 }, { name: "USP40", x: 1, y: 3 }] },
    { name: "Pulse", role: "Defender", weapons: [{ name: "UMP45", x: 0, y: 3 }, { name: "M1014", x: 1, y: 2 }, { name: "5.7 USG", x: 1, y: 3 }, { name: "M45 MEUSOC", x: 1, y: 3 }, { name: "Reaper MK2", x: 1, y: 4 }] },
    { name: "Rook", role: "Defender", weapons: [{ name: "MP5", x: 0, y: 13 }, { name: "P90", x: 0, y: 11 }, { name: "SG-CQB", x: 1, y: 2 }, { name: "Reaper MK2", x: 1, y: 4 }, { name: "P9", x: 1, y: 1 }, { name: "LFP586", x: 1, y: 3 }] },
    { name: "Sentry", role: "Defender", weapons: [{ name: "Commando 9", x: 1, y: 4 }, { name: "M870", x: 1, y: 2 }, { name: "TCSG12", x: 1, y: 21 }, { name: "C75 Auto", x: 1, y: 8 }, { name: "Super Shorty", x: 1, y: 2 }] },
    { name: "Skopos", role: "Defender", weapons: [{ name: "PCX-33", x: 1, y: 4 }, { name: "P229", x: 1, y: 3 }] },
    { name: "Smoke", role: "Defender", weapons: [{ name: "M590A1", x: 1, y: 2 }, { name: "FMG-9", x: 1, y: 9 }, { name: "P226 Mk 25", x: 1, y: 3 }, { name: "SMG-11", x: 1, y: 9 }] },
    { name: "Solis", role: "Defender", weapons: [{ name: "ITA12L", x: 1, y: 2 }, { name: "P90", x: 1, y: 6 }, { name: "SMG-11", x: 1, y: 9 }] },
    { name: "Tachanka", role: "Defender", weapons: [{ name: "DP27", x: 0, y: 3 }, { name: "9x19VSN", x: 1, y: 5 }, { name: "PMM", x: 1, y: 3 }, { name: "GSh-18", x: 1, y: 3 }, { name: "Bearing 9", x: 1, y: 8 }] },
    { name: "Thorn", role: "Defender", weapons: [{ name: "UZK50GI", x: 1, y: 5 }, { name: "M870", x: 1, y: 2 }, { name: "1911 TACOPS", x: 1, y: 3 }, { name: "C75 Auto", x: 1, y: 8 }] },
    { name: "Thunderbird", role: "Defender", weapons: [{ name: "SPAS-15", x: 1, y: 2 }, { name: "Spear .308", x: 1, y: 6 }, { name: "Bearing 9", x: 1, y: 8 }, { name: "Q-929", x: 1, y: 3 }, { name: "ITA12S", x: 1, y: 2 }] },
    { name: "Tubarao", role: "Defender", weapons: [{ name: "MPX", x: 1, y: 5 }, { name: "AR-15.50", x: 1, y: 7 }, { name: "P226 Mk 25", x: 1, y: 3 }] },
    { name: "Valkyrie", role: "Defender", weapons: [{ name: "MPX", x: 1, y: 5 }, { name: "SPAS-12", x: 1, y: 2 }, { name: "D-50", x: 1, y: 3 }] },
    { name: "Vigil", role: "Defender", weapons: [{ name: "K1A", x: 1, y: 6 }, { name: "BOSG.12.2", x: 0, y: 5 }, { name: "C75 Auto", x: 1, y: 8 }, { name: "SMG-12", x: 2, y: 10 }] },
    { name: "Wamai", role: "Defender", weapons: [{ name: "AUG A2", x: 1, y: 14 }, { name: "MP5K", x: 1, y: 6 }, { name: "Super Shorty", x: 1, y: 2 }, { name: "P12", x: 1, y: 2 }, { name: "Keratos .357", x: 1, y: 3 }] },
    { name: "Warden", role: "Defender", weapons: [{ name: "M590A1", x: 1, y: 2 }, { name: "MPX", x: 1, y: 5 }, { name: "P-10C", x: 1, y: 3 }, { name: "SMG-12", x: 2, y: 10 }] }
];
